### ISSUE TITLE
Error using svyUtils$Excel

### ISSUE THREAD

**Issue by wvitpr** [Servoy/svyUtils#35]
I am getting the following error in a production server but it works fine in developer version 2020.3.0.3562

sun.misc.InvalidJarIndexException: Invalid index
at sun.misc.URLClassPath$JarLoader.getResource(Unknown Source) ~[?:1.8.0_241]
at sun.misc.URLClassPath$JarLoader.getResource(Unknown Source) ~[?:1.8.0_241]
at sun.misc.URLClassPath.getResource(Unknown Source) ~[?:1.8.0_241]
at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_241]
at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_241]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_241]
at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_241]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
at org.mozilla.javascript.Kit.classOrNull(Kit.java:60) ~[js.jar:?]
at org.mozilla.javascript.NativeJavaPackage.getPkgProperty(NativeJavaPackage.java:129) ~[js.jar:?]
at org.mozilla.javascript.NativeJavaPackage.get(NativeJavaPackage.java:84) ~[js.jar:?]
at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:2357) ~[js.jar:?]
at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1557) ~[js.jar:?]
at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1550) ~[js.jar:?]
at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1248) ~[js.jar:?]
at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815) ~[js.jar:?]
at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109) ~[js.jar:?]
at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:399) ~[js.jar:?]
at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3534) ~[js.jar:?]
at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107) ~[js.jar:?]
at com.servoy.j2db.scripting.ScriptEngine.executeFunction(ScriptEngine.java:670) [j2db.jar:2020.3.0.3562]
at com.servoy.j2db.server.ngclient.component.EventExecutor.executeEvent(EventExecutor.java:234) [servoy_ngclient_2020.3.0.3562.jar:?]
at com.servoy.j2db.server.ngclient.DataAdapterList.executeEvent(DataAdapterList.java:126) [servoy_ngclient_2020.3.0.3562.jar:?]
at com.servoy.j2db.server.ngclient.WebFormComponent$FormcomponentEventHandler.executeEvent(WebFormComponent.java:240) [servoy_ngclient_2020.3.0.3562.jar:?]
at org.sablo.BaseWebObject.doExecuteEvent(BaseWebObject.java:335) [sablo_2020.3.0.3562.jar:?]
at org.sablo.BaseWebObject.executeEvent(BaseWebObject.java:324) [sablo_2020.3.0.3562.jar:?]
at org.sablo.services.server.FormServiceHandler.executeEvent(FormServiceHandler.java:137) [sablo_2020.3.0.3562.jar:?]
at com.servoy.j2db.server.ngclient.NGFormServiceHandler.executeEvent(NGFormServiceHandler.java:503) [servoy_ngclient_2020.3.0.3562.jar:?]
at org.sablo.services.server.FormServiceHandler.executeMethod(FormServiceHandler.java:84) [sablo_2020.3.0.3562.jar:?]
at com.servoy.j2db.server.ngclient.NGFormServiceHandler.executeMethod(NGFormServiceHandler.java:482) [servoy_ngclient_2020.3.0.3562.jar:?]
at org.sablo.websocket.WebsocketEndpoint$5.run(WebsocketEndpoint.java:408) [sablo_2020.3.0.3562.jar:?]
at org.sablo.eventthread.Event$1.run(Event.java:102) [sablo_2020.3.0.3562.jar:?]
at org.sablo.websocket.CurrentWindow.runForWindow(CurrentWindow.java:76) [sablo_2020.3.0.3562.jar:?]
at org.sablo.eventthread.Event.execute(Event.java:92) [sablo_2020.3.0.3562.jar:?]
at org.sablo.eventthread.EventDispatcher.dispatch(EventDispatcher.java:125) [sablo_2020.3.0.3562.jar:?]
at org.sablo.eventthread.EventDispatcher.run(EventDispatcher.java:89) [sablo_2020.3.0.3562.jar:?]
at com.servoy.j2db.server.ngclient.eventthread.NGEventDispatcher.run(NGEventDispatcher.java:55) [servoy_ngclient_2020.3.0.3562.jar:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

**Comment by jcompagner** [comment]
do you have anywhere in the WAR 0 byte/size jar files?
like a jdbc driver?

**Comment by wvitpr** [comment]
Hmm I have 3 files ? but they are not jars
beans.properties
lafs.properties
textbox_server.js

**Comment by jcompagner** [comment]
not it must be jars (or maybe zip)

this:

sun.misc.InvalidJarIndexException: Invalid index
at sun.misc.URLClassPath$JarLoader.getResource(Unknown Source) ~[?:1.8.0_241]

just means that there is a jar file in the classpath that is invalid so a jar is corrupt.

**Comment by wvitpr** [comment]
it would be nice if it said which jar is corrupt though?, how do I check for corrupt jars.

**Comment by jcompagner** [comment]
tell Oracle that, this is not servoy code.. but basic java.
